name: Plant Image Recognition

on:
  workflow_dispatch:
    inputs:
      image_id:
        description: 'Google Drive File ID'
        required: true
        type: string
        default: '1YAp0DpTZxAbVfMzGf7qpVxBTYK7tud4D'

jobs:
  recognize-plant:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Python dependencies
        run: |
          # We no longer need google-cloud-vision or pytesseract
          pip install requests
      
      - name: Process plant image
        run: python process_plant.py
        env:
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          # Add the new API Key secret
          GOOGLE_VISION_API_KEY: ${{ secrets.GOOGLE_VISION_API_KEY }}
          IMAGE_ID: ${{ inputs.image_id }}

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: recognition-results-${{ github.run_number }}
          path: |
            result.json
            result.log
          retention-days: 7
