name: Plant Image Recognition

# This trigger listens for an API request (a dispatch event)
# sent from a source like your Make.com scenario.
on:
  repository_dispatch:
    types: [coda_process_plant]

jobs:
  recognize-plant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install requests

      - name: Process plant image and Update Coda
        run: python process_plant.py
        env:
          # Google Drive and Vision API Keys
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_VISION_API_KEY: ${{ secrets.GOOGLE_VISION_API_KEY }}
          
          # PlantNet API Key
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          
          # Coda API Credentials
          CODA_API_TOKEN: ${{ secrets.CODA_API_TOKEN }}
          CODA_DOC_ID: ${{ secrets.CODA_DOC_ID }}
          CODA_TABLE_ID: ${{ secrets.CODA_TABLE_ID }}
          
          # Inputs from the Make.com webhook payload
          IMAGE_ID: ${{ github.event.client_payload.image_id }}
          ROW_ID: ${{ github.event.client_payload.row_id }}
