name: Plant Image Recognition

on:
  repository_dispatch:
    types: [coda_process_plant]

jobs:
  recognize-plant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: pip install requests google-generativeai Pillow

      - name: Process plant image and Update Coda
        run: python process_plant.py
        env:
          # All your API keys and secrets
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_VISION_API_KEY: ${{ secrets.GOOGLE_VISION_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CODA_API_TOKEN: ${{ secrets.CODA_API_TOKEN }}
          CODA_DOC_ID: ${{ secrets.CODA_DOC_ID }}
          CODA_TABLE_ID: ${{ secrets.CODA_TABLE_ID }}

          # All four inputs from the Make.com webhook payload
          IMAGE_ID: ${{ github.event.client_payload.image_id }}
          ROW_ID: ${{ github.event.client_payload.row_id }}
          IMAGE_NAME: ${{ github.event.client_payload.image_name }}
          PLANTNET_RESULT: ${{ github.event.client_payload.plantnet_result }} # <-- The new data
